#!/bin/bash

# Nach der gewünschten Distribution fragen
echo "==UberEats MinMaxxer simple Installer=="
echo "Which Linux-Distro are you using?"
echo "0 - Ubuntu"
echo "1 - Arch"
read -r distro

# Abhängig von der Eingabe die entsprechende Aktion ausführen
if [ "$distro" -eq 1 ]; then
    echo "Arch Linux erkannt. Installiere Maven mit pacman..."
    sudo pacman -S maven
elif [ "$distro" -eq 0 ]; then
    echo "Ubuntu erkannt. Installiere Maven mit apt..."
    sudo apt update
    sudo apt install -y maven
else
    echo "Ungültige Eingabe. Bitte 1 oder 0 eingeben."
fi
